### ISSUE TITLE
Use varWord encoding to make serialisation more efficient

### ISSUE THREAD

**Issue by ch3pjw** [concert/clapi#107]
https://github.com/concert/hs-varword allows us to use `git`'s compact variable-length word encodings easily in Haskell. We should use those encodings instead of fixed length encodings for some of the data CLAPI sends. E.g.:
 * Enums
 * List lengths
 * Word32/Word64 values
 * (Potentially) Int32/Int64

**Comment by foolswood** [comment]
Particularly useful for length encodings (where the numbers are likely to be small), which we use for lists and stuff in various places.

**Comment by ch3pjw** [comment]
:trophy:
