### ISSUE TITLE
Race on Enum redefinition leads to ambiguity

### ISSUE THREAD

**Issue by ch3pjw** [concert/clapi#125]
If a provider changes the definition of an enum whilst a update message is in flight from a client towards the provider (either client -> relay or relay -> provider), and the old enum value is in the range of the new enum value, the client message may end up being incorrect.

**Comment by foolswood** [comment]
We wondered about preventing reuse of values, which would make them more of a mapping than an index.

**Comment by ch3pjw** [comment]
We also discussed the merits of the client providing a hash of the type with each change, so as we could verify they had used the expected type when transmitting the data.

**Comment by ch3pjw** [comment]
Moved to https://gitlab.com/concert/clapi/issues/19
