### ISSUE TITLE
Child changes without explicit ContainerOps not broadcast to subscribers

### ISSUE THREAD

**Issue by foolswood** [concert/clapi#89]
The scenario this was seen in was:
- Client connects and subscribes to `/relay/clients`
- Provider (or any other client) connects
- No updates sent to client

**Comment by ch3pjw** [comment]
Offline discussion result: We should probably stop trying to "minimise" the bundle the Relay got sent and then forwarding it on, and instead "consume" that bundle to generate our initial revalidation structure. Validation should then produce a new bundle which is the "what actually changed" bundle, which would include any inferences we made about types and node children and have automagically removed any duplicate leaf data.
